zookeeper:
  image: confluent/zookeeper
  hostname: zookeeper
  ports:
    - '42181:2181'
    - '42888:2888'
    - '43888:3888'
kafka:
  image: confluent/kafka
  hostname: kafka
  links:
    - zookeeper
  environment:
    KAFKA_LOG_CLEANUP_POLICY: compact
  ports:
    - '49092:9092'
postgres:
  build: ./tmp
  dockerfile: Dockerfile.postgres
  hostname: postgres
  ports:
    - '45432:5432'
bottledwater:
  build: ./tmp
  dockerfile: Dockerfile.client
  hostname: bottledwater
  links:
    - postgres
    - kafka
psql:
  image: postgres:9.4
  links:
    - postgres
  command: 'sh -c ''exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres'''
kafka-tools:
  image: confluent/tools
  links:
    - zookeeper
    - kafka
  entrypoint: /confluent-tools.sh
